- callback
- promise
- async/await（promise 的语法糖）

# callback

# 使用

【一般用法】

```js
function getUser(id, callback) {
    setTimeout(() => {
        console.log('Reading a user from a database...');
        callback({ id:id, name:'lemon'});
    }, 2000)
}
```

调用：

```js
getUser(1, (user) => {
    console.log('User', user);
})
```

【嵌套】

```js
getUser(1, (user) => {
  getRepositories(user.name, (repos) => {
      console.log('Repos', repos)
  })
})

function getRepositories(username, callback) {
  setTimeout(() => {
      console.log('Calling API...')
      callback(['repo1', 'repo2', 'repo3']);
  }, 2000)
}

function getUser(id, callback) {
  setTimeout(() => {
      console.log('Reading a user from a database...');
      callback({ id:id, name:'lemon'});
  }, 2000)
}
```

## 回调地狱

在上面我们可以看见了嵌套的 callback，一旦需要的异步多了，就会不停地嵌套，这就变成了回调地狱。

异步的方法不利于阅读，我们追求用同步的方法书写异步。

## 扁平化回调

把

```js
getUser(1, (user) => {
  getRepositories(user.name, (repos) => {
      console.log('Repos', repos)
  })
})
```

变成：

```js
getUser(1, getCommits)

function getCommits(user) {
  getRepositories(user.name, displayCommits)
}
```

【最终效果】

```js
getUser(1, getCommits)

function getCommits(user) {
  getRepositories(user.name, displayCommits)
}

function displayCommits(repos) {
  console.log(repos);
}

function getRepositories(username, callback) {
  setTimeout(() => {
    console.log('Calling API...')
    callback(['repo1', 'repo2', 'repo3']);
  }, 2000)
}

function getUser(id, callback) {
  setTimeout(() => {
    console.log('Reading a user from a database...');
    callback({ id: id, name: 'lemon' });
  }, 2000)
}
```

# promise

## 使用

promise 是一个保存异步处理结果的容器，当一个异步操作完成后，它要么保存了值，要么保存了错误信息。

这个对象有三个阶段：

- pending：这个阶段的 promise 关联着某个异步操作。问题是我们无法知道此时的异步操作是马上执行，还是刚刚执行，或是即将出结果，我们都不知道。
- rejected：出现错误，执行失败，状态就变更。
- resolve：执行成功，状态变更。

状态只能重 pending => rejected 或 pending => resolve。

```js
const p = new Promise((resolve, reject) => {
    // kick off some async work
    // ...
    
    // success
    resolve(1);
    // error
    reject(err);
})
```

参数中的 resolve 和 reject 也是函数，成功就调用 resolve()，失败就调用 reject()。

```js
p.then( result => {
    // 此时的 result 就是 resolve 传递的参数
    console.log('result': result);
})
.catch( error => {
    throw error;
})
```

注意，then 接收两个参数，第一个参数是成功后的结果，第二个参数是失败后的结果。但我们常常使用第一个参数，错误使用 catch 捕捉。

【完整代码】

```js
const p = new Promise((resolve, reject) => {
  // kick off some async work
  // like this:
  setTimeout(() => {
    // success
    resolve(1);
    // error
    reject(new Error('message'));
  }, 5000);

})

p
  .then(result => {
    // 此时的 result 就是 resolve 传递的参数
    console.log('result', result);
  })
  .catch(error => {
    throw error;
  })
```

## promise 解决回调地狱

有了 promise，任何的异步操作我们都应该返回一个 promise。

重构上面的代码：

```js
getUser(1)
  .then(user => getRepositories(user.name))
  .then(repos => getCommits(repos[0]))
  .then(commits => console.log('Commits', commits))
  .catch(e => {
    throw e;
  })

function getUser(id) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log('Reading a user from a database...');
      resolve({ id: id, name: 'lemon' });
    }, 2000);
  });
}

function getRepositories(userName) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log('Calling API...')
      resolve(['repo1', 'repo2', 'repo3'])
    }, 2000);
  });
}

function getCommits(repo) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log('Calling GitHub API...');
      resolve(['Commit'])
    }, 2000);
  });
}
```

## 常用方法

- resolve：成功后调用的方法
- reject：失败时调用的方法，推荐传入一个 Error()
- then：两个 function 参数，第一个参数 function 成功时调用，参数是 resolve 传递过来的；第二个 function 参数可选，失败时调用，参数是 reject 传递过来的。通常只使用第一个参数。
- catch：捕捉错误，同 then 的第二个参数。

同时使用多个 promise：

- race：类方法，多个 Promise 任务同时执行，返回最先执行结束的 Promise 任务的结果，不管这个 Promise 结果是成功还是失败。 
- all：类方法，多个 Promise 任务同时执行。如果全部成功执行，则以数组的方式返回所有 Promise 任务的执行结果。 如果有一个 Promise 任务 rejected，则只返回 rejected 任务的结果。

# Async/Await

## 使用

```js
async function dispalyCommits() {
  try {
    const user = await getUser(1);
    const repos = await getRepositories(user.name);
    const commits = await getCommits(repos[0]);
    console.log(commits)
  } catch (e) {
    throw e;
  }
}

dispalyCommits()
```

async/await 是 promise 的语法糖，只有 promise 前面允许使用 await 字段，且 await 字段只能使用在 async 函数中。

使用 await 能够让我们像写同步代码一样写异步代码。

await 的执行是 Generator。

## 参考+必看

- [JS 高级之手写一个Promise,Generator,async和 await【近 1W字】](https://juejin.im/post/5df83b93f265da33f8652ccc#heading-13)